language: rust

rust:
  - stable
  - beta

matrix:
  fast_finish: true

cache:
  cargo: true
  directories:
    - deps

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libudev-dev

before_install:
  - if [[ ! -d deps ]]; then mkdir deps ; fi
  - pushd deps
  - wget https://www.veripool.org/ftp/verilator-3.916.tgz
  - unset VERILATOR_ROOT
  - tar xvzf verilator*.t*gz
  - pushd verilator*
  - "./configure"
  - make
  - sudo make install
  - popd
  - popd

install: cargo build --verbose --all
script: cargo test --verbose --all

before_deploy:
  - cargo build --release
  - strip target/release/narvie-cli
  - cp target/release/narvie-cli-$TRAVIS_TAG-$TARGET
deploy:
  if: env($TRAVIS_RUST_VERSION) = stable
  provider: releases
  api_key:
    secure: "XPNjhzAUhhOZ87jmpo3XYkfEP4CBOy3DLPVTVDIDGh6zc2jnYOPMxghz7fA9FH8Kgk6DFETDF/eyda5JEa6r2B/7gVBGYvS49P/hMs1OAXqXEaq6fa3F4O+SzqE8LI48KF794ORwzMv1e1gh/GDcrfqxi8f4HKtyf+6Jyrh5iDlCVXbbHkqKOpgX9I0c0UWkNuGnLP913VAYx8ZfwzxPhnIh0T5DGPs1dwC7lhN+eALvj052+Juj2HGwyPzzHKFamBD3oCSMvUG2YOXX0Vh3LhvZQs3P7G6YNVSMEVXluJpJqg3Te3FHovjSpPjTwQr55zHmbxorbM0tE0B8LcNBJOWryLUoKQ/EmFUiUj4jOCNkosR6kDg6081BS+5EGDgq2717eS79M7WLCDVDKC439/iapZTGfnH0LcVNfR+BsSFIYr9nsSgfWKNlgKs5xaTj0IPI3shLetCAYAqN/jAOkS7M1lbtI1g4xfVHlJkWFgEniKUwwLyJere2v1Pf+rEVWzwEj+PlIzYXwtMmXwZxQiOkRDIKsRWUrLapY5Q6XaGCFKkhX1UzNu+Z9nRwlhieU/PXy4D2NgrsBssLwN2HgIsh/41csc7YcBQAgqmNHcl5UfFj9AVpGcVFvSfhMVijha6gxMwTkyVuuhAWFa12K5a6zqUN8LftO6wnSXmau4o="
  file: target/release/narvie-cli-$TRAVIS_TAG-$TARGET
  skip_cleanup: true
  draft: true
  on:
    repo: physical-computation/narvie
    branch: master
