#!/bin/bash

set -e

cd RV32I_common
source ../module-list.sh

PROJECT=rv32i_ice40MDP

yosys -p "synth_ice40 -blif ../$PROJECT.blif;" $MODULES ../top.v

arachne-pnr -d 5k -P uwg30 -p ../$PROJECT.pcf ../$PROJECT.blif -o ../$PROJECT.asc

icepack ../$PROJECT.asc ../$PROJECT.bin

iceprog -S ../$PROJECT.bin
