#!/bin/bash

set -e

export NARVIE_ROOT=$(pwd)
source ./module-list.sh

cd sail

PROJECT=rv32i_ice40MDP

yosys -p "synth_ice40 -blif ../$PROJECT.blif;" $MODULES $NARVIE_VERILOG/top.v

arachne-pnr -d 5k -P uwg30 -p ../$PROJECT.pcf ../$PROJECT.blif -o ../$PROJECT.asc

icepack ../$PROJECT.asc ../$PROJECT.bin

iceprog -S ../$PROJECT.bin
