#!/bin/bash

#icebram -g 32 2047 > submodule/verilog/data_syn.hex

cd submodule

yosys -p "synth_ice40 -blif rv32i_ice40.blif;" submodule/verilog/adder.v submodule/verilog/cpu.v submodule/verilog/mux2to1.v submodule/verilog/alu_control.v submodule/verilog/pipeline_registers.v submodule/verilog/alu.v submodule/verilog/data_memory_iCE40UP5K.v submodule/verilog/program_counter.v submodule/verilog/branch_decide.v submodule/verilog/forwarding_unit.v submodule/verilog/branch_predictor.v submodule/verilog/imm_gen.v submodule/verilog/control_unit.v submodule/verilog/instruction_mem.v submodule/verilog/register_file_iCE40UP5K.v submodule/verilog/CSR_iCE40UP5K.v submodule/verilog/dataMem_mask_gen.v submodule/uart/baudgen_tx.v submodule/uart/uart_tx.v top.v

arachne-pnr -d 5k -P sg48 -p rv32i_ice40.pcf rv32i_ice40.blif -o rv32i_ice40.asc

#icebram submodule/verilog/data_syn.hex submodule/verilog/data.hex < rv32i_ice40.asc > rv32i_ice40.asc

icepack rv32i_ice40.asc rv32i_ice40.bin

iceprog -S rv32i_ice40.bin
