#!/bin/bash

cd submodule

verilator -Wall --cc ../top_sim.v verilog/adder.v verilog/cpu.v verilog/mux2to1.v verilog/alu_control.v verilog/pipeline_registers.v verilog/alu.v verilog/program_counter.v verilog/branch_decide.v verilog/forwarding_unit.v verilog/branch_predictor.v verilog/imm_gen.v verilog/control_unit.v verilog/register_file_iCE40UP5K.v verilog/CSR_iCE40UP5K.v verilog/dataMem_mask_gen.v uart/baudgen_tx.v uart/uart_tx.v uart/baudgen.vh simulation/data_memory.v simulation/instruction_mem.v config.vlt -Iuart  -Isubmodule --trace --exe ../top_sim.cpp -Mdir ../verilator_sim -CFLAGS "-g -O3"

make -j -C ../verilator_sim -f Vtop_sim.mk Vtop_sim

../verilator_sim/Vtop_sim

gtkwave ../verilator_sim/Vtop_sim.vcd
