#!/bin/bash

set -e

cd sail
source ../module-list.sh

verilator \
-Wall \
--cc ../testbench/top_sim.v $MODULES config.vlt \
-I$UART_RX \
--exe testbench/main.cpp testbench/testbench.cpp testbench/uartsim.cpp \
-Mdir ../verilator_sim \
-CFLAGS "-std=c++14 -g -O3"


make -j -C ../verilator_sim -f Vtop_sim.mk Vtop_sim

../verilator_sim/Vtop_sim

